# Generated by Django 5.1.4 on 2025-01-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('no_control', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Basico 1', 'Basico 1'), ('Basico 2', 'Basico 2'), ('Basico 3', 'Basico 3'), ('Basico 4', 'Basico 4'), ('Basico 5', 'Basico 5'), ('Intermedio 1', 'Intermedio 1'), ('Intermedio 2', 'Intermedio 2'), ('Intermedio 3', 'Intermedio 3'), ('Intermedio 4', 'Intermedio 4'), ('Intermedio 5', 'Intermedio 5'), ('Super Intensivo A1', 'Super Intensivo A1'), ('Super Intensivo B1', 'Super Intensivo B1'), ('Super Intensivo B1.1', 'Super Intensivo B1.1')], max_length=50)),
                ('grupo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('turno', models.CharField(choices=[('Lunes a Viernes', 'Lunes a Viernes'), ('Sabado y Domingo', 'Sabado y Domingo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=45)),
                ('apellido_docente', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4)),
                ('periodo', models.CharField(choices=[('Enero-junio A', 'Enero-junio A'), ('Enero-junio B', 'Enero-junio B'), ('Agosto-Diciembre A', 'Agosto-Diciembre A'), ('Agosto-Diciembre B', 'Agosto-Diciembre B'), ('Invierno', 'Invierno')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.TextField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.curso')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.periodo'),
        ),
    ]
