# Generated by Django 5.1.4 on 2025-01-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_curso_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.periodo'),
        ),
    ]
