# Generated by Django 5.1.4 on 2025-01-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_curso_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
    ]
