# Generated by Django 5.1.4 on 2025-01-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_curso_docente_curso_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
    ]
